language: php

git:
  quiet: true
  depth: 3

php:
 - 5.4
 - 5.5
 - 5.6
 # In Travis CI PHP 7.0.15 comes with PHPUnit 5.7.6, which is compatible with
 # earlier versions of itself hence RackTables tests can work on older PHP
 # versions too (a major advantage of the test matrix). Later PHP versions come
 # with PHPUnit 6, which is compatible with itself only due to namespaces.
 - 7.0.15

matrix:
  fast_finish: true

services:
 - mysql

before_script:
 - ./tests/travis_setup_mysql.sh racktables_unittest racktables travistest

script:
 - ./tests/express.sh
 - mysql -u racktables -ptravistest racktables_unittest < scripts/init-sample-racks.sql
 - DESTDIR=/tmp make install
